export const WORKLOAD_STATUSES = {
  DEGRADED: 'DEGRADED',
  UNKNOWN: 'UNKNOWN',
  OPERATIONAL: 'OPERATIONAL',
  DISRUPTED: 'DISRUPTED',
};

export const STATUS_PRIORITY = {
  CRITICAL: 3,
  WARNING: 2,
  HEALTHY: 1,
  UNKNOWN: 0,
};
